baseurl = "https://eclipse.dev/nattable/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Nebula NatTable"
theme = "hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = []
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "NatTable is a powerful and flexible SWT table/grid widget that is built to handle very large data sets, real-time updates, dynamic styling, and more."
  seo_title_suffix = " | Nebula NatTable"
  keywords = ["eclipse", "project", "plug-ins", "plugins", "swt", "nattable", "grid"]
  news_count = 3
  gcse = "011805775785170369411:p3ec0igo0qq"
  gcse_result_url = "https://www.eclipse.org/home/search/"
  header_wrapper_class = "header_wrapper_class"
  call_for_action_text = "Download"
  call_for_action_url = "/nattable/download/"
  call_for_action_icon = "fa-download"
  layout_style = "astro"
  hide_ad = false
  featured_content_publish_target = "eclipse_org"
  sidebar_layout = "default"
# js = ""
# styles = ""
# logo = ""
# favicon = ""
# share_img = ""
# logo_width = ""
# header_left_classes = ""
# main_menu_wrapper_classes = ""
# projects_working_group = ""
# show_events = true
# table_classes = "table table-bordered"
# hide_cfa_same_page = true
# show_collapsible_menu = true

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  tag = "tags"

[Author]
  name = "Dirk Fauth, Edwin Park, Stephan Wahlbrink"
  email = "nattable-dev@eclipse.org"

[permalinks]
#  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.sidebar]]
  name = "NatTable (Home)"
  url = "/"
  weight = 1
  identifier = "home"

[[menu.sidebar]]
  parent ="home"
  name = "About this Project"
  url = "https://projects.eclipse.org/projects/technology.nebula.nattable/"
  weight = 1
  pre = "<i class=\"fa fa-caret-right fa-fw\"></i>"

[[menu.sidebar]]
  parent ="home"
  name = "Downloads"
  url = "/download/"
  weight = 2
  pre = "<i class=\"fa fa-caret-right fa-fw\"></i>"

[[menu.sidebar]]
  parent ="home"
  name = "News"
  url = "/news/"
  weight = 3
  pre = "<i class=\"fa fa-caret-right fa-fw\"></i>"

[[menu.sidebar]]
  parent ="home"
  name = "Documentation"
  url = "https://github.com/eclipse-nattable/nattable/wiki/"
  weight = 4
  pre = "<i class=\"fa fa-caret-right fa-fw\"></i>"

[[menu.sidebar]]
  parent ="home"
  name = "Publications"
  url = "/Publications/"
  weight = 5
  pre = "<i class=\"fa fa-caret-right fa-fw\"></i>"

[[menu.sidebar]]
  parent ="home"
  name = "Support"
  url = "/support/"
  weight = 6
  pre = "<i class=\"fa fa-caret-right fa-fw\"></i>"

[[menu.sidebar]]
  parent ="home"
  name = "Try it!"
  url = "/examples/"
  weight = 7
  pre = "<i class=\"fa fa-caret-right fa-fw\"></i>"

# Uncomment [[menu.main]] to hide the default EF menu
# or to define your own menu links.

# [[menu.main]]